# This workflow will enforce FIREWHEEL ecosystem standard linting

name: Lint

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  call-firewheel-linting:
    name: FIREWHEEL linting
    # Use the FIREWHEEL CI repo for both the workflow and its composite actions
    uses: sandialabs/firewheel_ci/.github/workflows/linting.yml@main
    with:
      actions-ref: main
